#!/bin/bash

temporary_file=traceroute.txt
final_file=traceroute_measure.csv

# Declare an array of string with type  "iperf.par2.as49434.net" => Serveur down ?
declare -a Servers=("iperf.biznetnetworks.com" "iperf.scottlinux.com" "iperf.eenet.ee" "speedtest.uztelecom.uz" "lille.testdebit.info" "speedtest.serverius.net")

currentdate=`date +"%Y-%m-%d %T"`


echo "${currentdate}" >> "${temporary_file}"

# Iterate the string array using for loop
for server in ${Servers[@]}; do
   echo "$(traceroute -n -m 20 $server)" >> "${temporary_file}"
done

#python3 traceroute.py "${temporary_file}" "${final_file}"
